[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.37.37",
    "flask>=3.1.0",
    "matplotlib>=3.10.1",
    "pytz>=2025.2",
    "reportlab>=4.4.0",
]
